version: "1"
services:

  mysql:
    restart: always
    image: ${MYSQL_IMAGE}
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      TZ: Asia/Shanghai
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend

  redis:
    restart: always
    image: ${REDIS_IMAGE}
    container_name: redis
    volumes:
      - ./redis/redis.conf:/usr/local/redis/redis.conf
      - ./redis/data:/opt/apache/redis/data
    ports:
      - "6379:6379"
    command: ["sh","-c","/usr/local/bin/redis-server /usr/local/redis/redis.conf ; tail -f /usr/local/redis/redis.log"]
    networks:
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
